process_names:
  - name: "backend-main"
    cmdline:
      - '.*/gunicorn'
      - '.*run:app.*'

  - name: "backend-flask"
    comm:
      - 'python'
    cmdline:
      - '.*run\.py.*'

  - name: "frontend"
    comm:
      - 'next-server (v'
      - 'next-server'

  - name: "database-postgres"
    cmdline:
      - '.*postgres.*'

  - name: "otel-collector"
    cmdline:
      - '.*otelcol.*'

  - name: "prometheus"
    cmdline:
      - '.*prometheus.*'

  - name: "grafana"
    cmdline:
      - '.*grafana.*'

  - name: "loki"
    comm:
      - 'loki'

  - name: "promtail"
    comm:
      - 'promtail'
