global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  # Job to scrape Prometheus's own metrics
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Prometheus server default port

  # Job to scrape metrics from the OpenTelemetry Collector
  - job_name: 'otel-collector'
    static_configs:
      # The OTel Collector usually exposes Prometheus metrics at a specific endpoint/port
      - targets: ['otel:8889'] # Common default for OTel Collector Prometheus exporter
    # Example: If OTel endpoint has a specific metrics path, define it here
    metrics_path: /metrics

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: /metrics

  - job_name: 'process-exporter'
    static_configs:
      - targets: ['process-exporter:9256']
    metrics_path: /metrics
